import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { noticesApi } from '@/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import { Megaphone, Plus, Pencil, Trash2, Printer, Sparkles, MessageSquare } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { aiApi } from '@/api';

const AUDIENCES = ['ALL', 'TEACHERS', 'STUDENTS', 'PARENTS'];
const AUDIENCE_LABELS = { ALL: 'Everyone', TEACHERS: 'Teachers', STUDENTS: 'Students', PARENTS: 'Parents' };
const audienceLabel = (t, a) => t(`notices.audience${a.charAt(0)}${a.slice(1).toLowerCase()}`, { defaultValue: AUDIENCE_LABELS[a] || AUDIENCE_LABELS.ALL });
const companyId = () => localStorage.getItem('easybooks_active_company') || '';

function NoticeDialog({ open, onClose, notice }) {
  const { t } = useTranslation();
  const qc = useQueryClient();
  const isEdit = !!notice;
  const [form, setForm] = useState({
    title: notice?.title || '',
    content: notice?.content || '',
    targetAudience: notice?.targetAudience || 'ALL',
    expiresAt: notice?.expiresAt ? notice.expiresAt.split('T')[0] : '',
  });
  const [aiLoading, setAiLoading] = useState(false);

  const save = useMutation({
    mutationFn: (d) =>
      isEdit
        ? noticesApi.update(notice.id, d)
        : noticesApi.create({ ...d, companyId: companyId() }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['school-notices'] });
      toast.success(isEdit ? t('notices.noticeUpdated', { defaultValue: 'Notice updated' }) : t('notices.noticePosted', { defaultValue: 'Notice posted' }));
      onClose();
    },
    onError: (e) => toast.error(e.response?.data?.message || t('notices.failedToSave', { defaultValue: 'Failed to save' })),
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!form.title.trim() || !form.content.trim()) return toast.error(t('notices.titleContentRequired', { defaultValue: 'Title and content are required' }));
    save.mutate({ ...form, expiresAt: form.expiresAt || undefined });
  };

  async function generateWithAI() {
    if (!form.title.trim()) { toast.error(t('notices.enterTopicFirst', { defaultValue: 'Enter a topic/title first so AI knows what to write' })); return; }
    setAiLoading(true);
    try {
      const res = await aiApi.generateNotice({
        topic: form.title,
        targetAudience: form.targetAudience,
        tone: 'formal',
      });
      setForm(p => ({ ...p, title: res.data.title || p.title, content: res.data.content }));
      toast.success(t('notices.generatedByAI', { defaultValue: 'Notice generated by AI' }));
    } catch (e) {
      toast.error(e?.response?.data?.message || t('notices.aiFailed', { defaultValue: 'AI generation failed — check GEMINI_API_KEY' }));
    } finally {
      setAiLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>{isEdit ? t('notices.editNotice', { defaultValue: 'Edit Notice' }) : t('notices.postNotice', { defaultValue: 'Post Notice' })}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1">
            <div className="flex items-center justify-between">
              <Label>{t('notices.title', { defaultValue: 'Title *' })}</Label>
              <button
                type="button"
                onClick={generateWithAI}
                disabled={aiLoading}
                className="flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full bg-violet-50 text-violet-700 hover:bg-violet-100 transition-colors disabled:opacity-50"
              >
                <Sparkles className="w-3 h-3" />
                {aiLoading ? t('notices.generating', { defaultValue: 'Generating…' }) : t('notices.generateWithAI', { defaultValue: 'Generate with AI' })}
              </button>
            </div>
            <Input value={form.title} onChange={e => setForm(p => ({ ...p, title: e.target.value }))} placeholder={t('notices.titlePlaceholder', { defaultValue: 'e.g. Annual Sports Day 2081' })} />
          </div>
          <div className="space-y-1">
            <Label>{t('notices.content', { defaultValue: 'Content *' })}</Label>
            <Textarea
              value={form.content}
              onChange={e => setForm(p => ({ ...p, content: e.target.value }))}
              placeholder={t('notices.contentPlaceholder', { defaultValue: 'Write your notice here…' })}
              rows={6}
            />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label>{t('notices.audience', { defaultValue: 'Audience' })}</Label>
              <Select value={form.targetAudience} onValueChange={v => setForm(p => ({ ...p, targetAudience: v }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {AUDIENCES.map(a => <SelectItem key={a} value={a}>{audienceLabel(t, a)}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1">
              <Label>{t('notices.expiresOn', { defaultValue: 'Expires On' })}</Label>
              <input
                type="date"
                value={form.expiresAt}
                onChange={e => setForm(p => ({ ...p, expiresAt: e.target.value }))}
                className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm"
              />
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t('notices.cancel', { defaultValue: 'Cancel' })}</Button>
            <Button type="submit" disabled={save.isPending}>
              {save.isPending ? t('notices.posting', { defaultValue: 'Posting…' }) : isEdit ? t('notices.update', { defaultValue: 'Update' }) : t('notices.postNotice', { defaultValue: 'Post Notice' })}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function printNotice(n) {
  const w = window.open('', '_blank');
  w.document.write(`
    <html><head><title>Notice</title>
    <style>body{font-family:serif;max-width:700px;margin:40px auto;padding:0 20px}
    h2{text-align:center;border-bottom:2px solid #000;padding-bottom:8px}
    .meta{display:flex;justify-content:space-between;margin:12px 0;font-size:13px;color:#555}
    .content{white-space:pre-wrap;line-height:1.8;margin-top:20px;font-size:15px}
    .footer{margin-top:60px;text-align:right;font-size:13px}
    @media print{button{display:none}}
    </style></head>
    <body>
    <h2>${n.title}</h2>
    <div class="meta">
      <span>Date: ${format(new Date(n.createdAt), 'MMMM d, yyyy')}</span>
      <span>For: ${AUDIENCE_LABELS[n.targetAudience] || 'Everyone'}</span>
    </div>
    <div class="content">${n.content}</div>
    <div class="footer">
      <p>_______________________</p>
      <p>Principal / Administration</p>
    </div>
    <br><button onclick="window.print()">Print</button>
    </body></html>
  `);
  w.document.close();
  setTimeout(() => w.print(), 300);
}

export default function Notices() {
  const { t } = useTranslation();
  const qc = useQueryClient();
  const [dialog, setDialog] = useState({ open: false, notice: null });
  const [search, setSearch] = useState('');

  const { data: notices = [], isLoading } = useQuery({
    queryKey: ['school-notices'],
    queryFn: () => noticesApi.list().then(r => r.data),
  });

  const remove = useMutation({
    mutationFn: (id) => noticesApi.remove(id),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['school-notices'] }); toast.success(t('notices.noticeDeleted', { defaultValue: 'Notice deleted' })); },
    onError: (e) => toast.error(e.response?.data?.message || t('notices.cannotDelete', { defaultValue: 'Cannot delete' })),
  });

  const filtered = notices.filter(n =>
    n.title.toLowerCase().includes(search.toLowerCase()) ||
    n.content.toLowerCase().includes(search.toLowerCase())
  );

  const isExpired = (n) => n.expiresAt && new Date(n.expiresAt) < new Date();

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Megaphone className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold">{t('notices.noticeBoard', { defaultValue: 'Notice Board' })}</h1>
        </div>
        <Button onClick={() => setDialog({ open: true, notice: null })}>
          <Plus className="h-4 w-4 mr-1" /> {t('notices.postNotice', { defaultValue: 'Post Notice' })}
        </Button>
      </div>

      <Input
        placeholder={t('notices.searchPlaceholder', { defaultValue: 'Search notices…' })}
        value={search}
        onChange={e => setSearch(e.target.value)}
        className="max-w-sm"
      />

      {isLoading ? (
        <div className="text-center py-12 text-muted-foreground">{t('notices.loading', { defaultValue: 'Loading…' })}</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">{t('notices.noNotices', { defaultValue: 'No notices yet. Post your first notice.' })}</div>
      ) : (
        <div className="space-y-3">
          {filtered.map(n => (
            <div key={n.id} className={`rounded-lg border p-4 bg-card ${isExpired(n) ? 'opacity-60' : ''}`}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-semibold text-base">{n.title}</h3>
                    <Badge variant="outline" className="text-xs">{audienceLabel(t, n.targetAudience)}</Badge>
                    {isExpired(n) && <Badge variant="secondary" className="text-xs">{t('notices.expired', { defaultValue: 'Expired' })}</Badge>}
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">
                    {t('notices.posted', { defaultValue: 'Posted: {{date}}', date: format(new Date(n.createdAt), 'dd MMM yyyy') })}
                    {n.expiresAt && ` · ${t('notices.expires', { defaultValue: 'Expires: {{date}}', date: format(new Date(n.expiresAt), 'dd MMM yyyy') })}`}
                  </p>
                  <p className="mt-2 text-sm whitespace-pre-wrap line-clamp-3">{n.content}</p>
                </div>
                <div className="flex gap-1 shrink-0">
                  <Button size="icon" variant="ghost" onClick={() => printNotice(n)} title={t('notices.print', { defaultValue: 'Print' })}>
                    <Printer className="h-4 w-4" />
                  </Button>
                  <Button size="icon" variant="ghost" title={t('notices.broadcastSms', { defaultValue: 'Broadcast SMS to all guardians' })} onClick={async () => {
                    try {
                      const res = await noticesApi.broadcastSms(n.id);
                      toast.success(t('notices.smsSent', { defaultValue: 'SMS sent: {{sent}} delivered, {{failed}} failed', sent: res.data.sent, failed: res.data.failed }));
                    } catch (e) {
                      toast.error(e?.response?.data?.message || t('notices.smsFailed', { defaultValue: 'SMS failed — check SMS_API_KEY' }));
                    }
                  }}>
                    <MessageSquare className="h-4 w-4 text-violet-600" />
                  </Button>
                  <Button size="icon" variant="ghost" onClick={() => setDialog({ open: true, notice: n })}>
                    <Pencil className="h-4 w-4" />
                  </Button>
                  <Button size="icon" variant="ghost" onClick={() => { if (window.confirm(t('notices.deleteConfirm', { defaultValue: 'Delete this notice?' }))) remove.mutate(n.id); }}>
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {dialog.open && (
        <NoticeDialog
          open={dialog.open}
          onClose={() => setDialog({ open: false, notice: null })}
          notice={dialog.notice}
        />
      )}
    </div>
  );
}
