import { z } from 'zod';
export declare const EmployeeStatusEnum: z.ZodEnum<["ACTIVE", "INACTIVE", "ON_LEAVE"]>;
export declare const CreateEmployeeSchema: z.ZodObject<{
    companyId: z.ZodString;
    name: z.ZodString;
    employeeId: z.ZodString;
    department: z.ZodOptional<z.ZodString>;
    designation: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    dateOfJoining: z.ZodOptional<z.ZodString>;
    basicSalary: z.ZodDefault<z.ZodNumber>;
    allowances: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodNumber>>;
    bankName: z.ZodOptional<z.ZodString>;
    bankAccount: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["ACTIVE", "INACTIVE", "ON_LEAVE"]>>;
}, "strip", z.ZodTypeAny, {
    status: "ACTIVE" | "INACTIVE" | "ON_LEAVE";
    name: string;
    companyId: string;
    employeeId: string;
    basicSalary: number;
    bankAccount?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    department?: string | undefined;
    designation?: string | undefined;
    panNumber?: string | undefined;
    dateOfJoining?: string | undefined;
    allowances?: Record<string, number> | undefined;
    bankName?: string | undefined;
}, {
    name: string;
    companyId: string;
    employeeId: string;
    status?: "ACTIVE" | "INACTIVE" | "ON_LEAVE" | undefined;
    bankAccount?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    department?: string | undefined;
    designation?: string | undefined;
    panNumber?: string | undefined;
    dateOfJoining?: string | undefined;
    basicSalary?: number | undefined;
    allowances?: Record<string, number> | undefined;
    bankName?: string | undefined;
}>;
export declare const UpdateEmployeeSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["ACTIVE", "INACTIVE", "ON_LEAVE"]>>>;
    bankAccount: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    email: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    name: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    phone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    employeeId: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    designation: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    panNumber: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateOfJoining: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    basicSalary: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    allowances: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodNumber>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    status?: "ACTIVE" | "INACTIVE" | "ON_LEAVE" | undefined;
    bankAccount?: string | undefined;
    email?: string | undefined;
    name?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    employeeId?: string | undefined;
    department?: string | undefined;
    designation?: string | undefined;
    panNumber?: string | undefined;
    dateOfJoining?: string | undefined;
    basicSalary?: number | undefined;
    allowances?: Record<string, number> | undefined;
    bankName?: string | undefined;
}, {
    status?: "ACTIVE" | "INACTIVE" | "ON_LEAVE" | undefined;
    bankAccount?: string | undefined;
    email?: string | undefined;
    name?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    employeeId?: string | undefined;
    department?: string | undefined;
    designation?: string | undefined;
    panNumber?: string | undefined;
    dateOfJoining?: string | undefined;
    basicSalary?: number | undefined;
    allowances?: Record<string, number> | undefined;
    bankName?: string | undefined;
}>;
export type CreateEmployeeDTO = z.infer<typeof CreateEmployeeSchema>;
export type UpdateEmployeeDTO = z.infer<typeof UpdateEmployeeSchema>;
