import { z } from 'zod';
export declare const CreateInventoryItemSchema: z.ZodObject<{
    companyId: z.ZodString;
    partNumber: z.ZodOptional<z.ZodString>;
    itemName: z.ZodOptional<z.ZodString>;
    brand: z.ZodOptional<z.ZodString>;
    modelNo: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    application: z.ZodOptional<z.ZodString>;
    imageUrl: z.ZodOptional<z.ZodString>;
    quantity: z.ZodDefault<z.ZodNumber>;
    unit: z.ZodDefault<z.ZodString>;
    unitPurchasePrice: z.ZodDefault<z.ZodNumber>;
    unitSellingPrice: z.ZodDefault<z.ZodNumber>;
    defaultDiscountPercent: z.ZodDefault<z.ZodNumber>;
    stockLocation: z.ZodOptional<z.ZodString>;
    lowStockThreshold: z.ZodDefault<z.ZodNumber>;
    agingDays: z.ZodOptional<z.ZodNumber>;
    vendorId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    companyId: string;
    quantity: number;
    unit: string;
    unitPurchasePrice: number;
    unitSellingPrice: number;
    defaultDiscountPercent: number;
    lowStockThreshold: number;
    partNumber?: string | undefined;
    itemName?: string | undefined;
    brand?: string | undefined;
    modelNo?: string | undefined;
    description?: string | undefined;
    application?: string | undefined;
    imageUrl?: string | undefined;
    stockLocation?: string | undefined;
    agingDays?: number | undefined;
    vendorId?: string | undefined;
}, {
    companyId: string;
    partNumber?: string | undefined;
    itemName?: string | undefined;
    brand?: string | undefined;
    modelNo?: string | undefined;
    description?: string | undefined;
    application?: string | undefined;
    imageUrl?: string | undefined;
    quantity?: number | undefined;
    unit?: string | undefined;
    unitPurchasePrice?: number | undefined;
    unitSellingPrice?: number | undefined;
    defaultDiscountPercent?: number | undefined;
    stockLocation?: string | undefined;
    lowStockThreshold?: number | undefined;
    agingDays?: number | undefined;
    vendorId?: string | undefined;
}>;
export declare const UpdateInventoryItemSchema: z.ZodObject<{
    partNumber: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    itemName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    brand: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    modelNo: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    application: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    imageUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    quantity: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    unit: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    unitPurchasePrice: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    unitSellingPrice: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    defaultDiscountPercent: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    stockLocation: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    lowStockThreshold: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    agingDays: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    vendorId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    partNumber?: string | undefined;
    itemName?: string | undefined;
    brand?: string | undefined;
    modelNo?: string | undefined;
    description?: string | undefined;
    application?: string | undefined;
    imageUrl?: string | undefined;
    quantity?: number | undefined;
    unit?: string | undefined;
    unitPurchasePrice?: number | undefined;
    unitSellingPrice?: number | undefined;
    defaultDiscountPercent?: number | undefined;
    stockLocation?: string | undefined;
    lowStockThreshold?: number | undefined;
    agingDays?: number | undefined;
    vendorId?: string | undefined;
}, {
    partNumber?: string | undefined;
    itemName?: string | undefined;
    brand?: string | undefined;
    modelNo?: string | undefined;
    description?: string | undefined;
    application?: string | undefined;
    imageUrl?: string | undefined;
    quantity?: number | undefined;
    unit?: string | undefined;
    unitPurchasePrice?: number | undefined;
    unitSellingPrice?: number | undefined;
    defaultDiscountPercent?: number | undefined;
    stockLocation?: string | undefined;
    lowStockThreshold?: number | undefined;
    agingDays?: number | undefined;
    vendorId?: string | undefined;
}>;
export type CreateInventoryItemDTO = z.infer<typeof CreateInventoryItemSchema>;
export type UpdateInventoryItemDTO = z.infer<typeof UpdateInventoryItemSchema>;
