import { z } from 'zod';
export declare const CreateMemoDocumentSchema: z.ZodObject<{
    companyId: z.ZodString;
    category: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodOptional<z.ZodString>;
    dateAd: z.ZodString;
    dateBs: z.ZodOptional<z.ZodString>;
    documentType: z.ZodOptional<z.ZodString>;
    attachments: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    referenceId: z.ZodOptional<z.ZodString>;
    clientName: z.ZodOptional<z.ZodString>;
    clientContact: z.ZodOptional<z.ZodString>;
    clientAddress: z.ZodOptional<z.ZodString>;
    vendorName: z.ZodOptional<z.ZodString>;
    vendorContact: z.ZodOptional<z.ZodString>;
    vendorPan: z.ZodOptional<z.ZodString>;
    assignedTo: z.ZodOptional<z.ZodString>;
    startDate: z.ZodOptional<z.ZodString>;
    endDate: z.ZodOptional<z.ZodString>;
    deliveryDate: z.ZodOptional<z.ZodString>;
    dueDate: z.ZodOptional<z.ZodString>;
    validUntil: z.ZodOptional<z.ZodString>;
    docType: z.ZodOptional<z.ZodString>;
    linkedReference: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    amount: z.ZodOptional<z.ZodNumber>;
    documentUrl: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    companyId: string;
    dateAd: string;
    status?: string | undefined;
    description?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientAddress?: string | undefined;
    amount?: number | undefined;
    vendorName?: string | undefined;
    vendorContact?: string | undefined;
    startDate?: string | undefined;
    endDate?: string | undefined;
    dateBs?: string | undefined;
    category?: string | undefined;
    referenceId?: string | undefined;
    title?: string | undefined;
    content?: string | undefined;
    documentType?: string | undefined;
    attachments?: string[] | undefined;
    vendorPan?: string | undefined;
    assignedTo?: string | undefined;
    deliveryDate?: string | undefined;
    dueDate?: string | undefined;
    validUntil?: string | undefined;
    docType?: string | undefined;
    linkedReference?: string | undefined;
    documentUrl?: string | undefined;
}, {
    companyId: string;
    dateAd: string;
    status?: string | undefined;
    description?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientAddress?: string | undefined;
    amount?: number | undefined;
    vendorName?: string | undefined;
    vendorContact?: string | undefined;
    startDate?: string | undefined;
    endDate?: string | undefined;
    dateBs?: string | undefined;
    category?: string | undefined;
    referenceId?: string | undefined;
    title?: string | undefined;
    content?: string | undefined;
    documentType?: string | undefined;
    attachments?: string[] | undefined;
    vendorPan?: string | undefined;
    assignedTo?: string | undefined;
    deliveryDate?: string | undefined;
    dueDate?: string | undefined;
    validUntil?: string | undefined;
    docType?: string | undefined;
    linkedReference?: string | undefined;
    documentUrl?: string | undefined;
}>;
export declare const UpdateMemoDocumentSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    clientName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    clientContact: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    clientAddress: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateAd: z.ZodOptional<z.ZodString>;
    amount: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    vendorName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    vendorContact: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    startDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    endDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateBs: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    category: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    referenceId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    title: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    content: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    documentType: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    attachments: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    vendorPan: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    assignedTo: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    deliveryDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dueDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    validUntil: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    docType: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    linkedReference: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    documentUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    status?: string | undefined;
    description?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientAddress?: string | undefined;
    dateAd?: string | undefined;
    amount?: number | undefined;
    vendorName?: string | undefined;
    vendorContact?: string | undefined;
    startDate?: string | undefined;
    endDate?: string | undefined;
    dateBs?: string | undefined;
    category?: string | undefined;
    referenceId?: string | undefined;
    title?: string | undefined;
    content?: string | undefined;
    documentType?: string | undefined;
    attachments?: string[] | undefined;
    vendorPan?: string | undefined;
    assignedTo?: string | undefined;
    deliveryDate?: string | undefined;
    dueDate?: string | undefined;
    validUntil?: string | undefined;
    docType?: string | undefined;
    linkedReference?: string | undefined;
    documentUrl?: string | undefined;
}, {
    status?: string | undefined;
    description?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientAddress?: string | undefined;
    dateAd?: string | undefined;
    amount?: number | undefined;
    vendorName?: string | undefined;
    vendorContact?: string | undefined;
    startDate?: string | undefined;
    endDate?: string | undefined;
    dateBs?: string | undefined;
    category?: string | undefined;
    referenceId?: string | undefined;
    title?: string | undefined;
    content?: string | undefined;
    documentType?: string | undefined;
    attachments?: string[] | undefined;
    vendorPan?: string | undefined;
    assignedTo?: string | undefined;
    deliveryDate?: string | undefined;
    dueDate?: string | undefined;
    validUntil?: string | undefined;
    docType?: string | undefined;
    linkedReference?: string | undefined;
    documentUrl?: string | undefined;
}>;
export type CreateMemoDocumentDTO = z.infer<typeof CreateMemoDocumentSchema>;
export type UpdateMemoDocumentDTO = z.infer<typeof UpdateMemoDocumentSchema>;
