import { z } from 'zod';
export declare const TransactionTypeEnum: z.ZodEnum<["CASH", "BANK", "QR", "CHEQUE", "CREDIT"]>;
export declare const TransactionCategoryEnum: z.ZodEnum<["INCOME", "EXPENSE", "TRANSFER", "INVESTMENT", "HAND_OUTS"]>;
export declare const TransactionStatusEnum: z.ZodEnum<["PENDING", "COMPLETED", "CANCELLED"]>;
export declare const CreateTransactionSchema: z.ZodObject<{
    companyId: z.ZodString;
    dateAd: z.ZodString;
    dateBs: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["CASH", "BANK", "QR", "CHEQUE", "CREDIT"]>;
    category: z.ZodEnum<["INCOME", "EXPENSE", "TRANSFER", "INVESTMENT", "HAND_OUTS"]>;
    amount: z.ZodNumber;
    description: z.ZodOptional<z.ZodString>;
    partyName: z.ZodOptional<z.ZodString>;
    reference: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["PENDING", "COMPLETED", "CANCELLED"]>>;
    debitAccountId: z.ZodOptional<z.ZodString>;
    creditAccountId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "CASH" | "CHEQUE" | "QR" | "CREDIT" | "BANK";
    status: "PENDING" | "COMPLETED" | "CANCELLED";
    companyId: string;
    dateAd: string;
    amount: number;
    category: "INCOME" | "EXPENSE" | "TRANSFER" | "INVESTMENT" | "HAND_OUTS";
    description?: string | undefined;
    debitAccountId?: string | undefined;
    creditAccountId?: string | undefined;
    dateBs?: string | undefined;
    partyName?: string | undefined;
    reference?: string | undefined;
}, {
    type: "CASH" | "CHEQUE" | "QR" | "CREDIT" | "BANK";
    companyId: string;
    dateAd: string;
    amount: number;
    category: "INCOME" | "EXPENSE" | "TRANSFER" | "INVESTMENT" | "HAND_OUTS";
    status?: "PENDING" | "COMPLETED" | "CANCELLED" | undefined;
    description?: string | undefined;
    debitAccountId?: string | undefined;
    creditAccountId?: string | undefined;
    dateBs?: string | undefined;
    partyName?: string | undefined;
    reference?: string | undefined;
}>;
export declare const UpdateTransactionSchema: z.ZodObject<{
    type: z.ZodOptional<z.ZodEnum<["CASH", "BANK", "QR", "CHEQUE", "CREDIT"]>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["PENDING", "COMPLETED", "CANCELLED"]>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateAd: z.ZodOptional<z.ZodString>;
    amount: z.ZodOptional<z.ZodNumber>;
    debitAccountId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    creditAccountId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateBs: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    category: z.ZodOptional<z.ZodEnum<["INCOME", "EXPENSE", "TRANSFER", "INVESTMENT", "HAND_OUTS"]>>;
    partyName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    reference: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    type?: "CASH" | "CHEQUE" | "QR" | "CREDIT" | "BANK" | undefined;
    status?: "PENDING" | "COMPLETED" | "CANCELLED" | undefined;
    description?: string | undefined;
    dateAd?: string | undefined;
    amount?: number | undefined;
    debitAccountId?: string | undefined;
    creditAccountId?: string | undefined;
    dateBs?: string | undefined;
    category?: "INCOME" | "EXPENSE" | "TRANSFER" | "INVESTMENT" | "HAND_OUTS" | undefined;
    partyName?: string | undefined;
    reference?: string | undefined;
}, {
    type?: "CASH" | "CHEQUE" | "QR" | "CREDIT" | "BANK" | undefined;
    status?: "PENDING" | "COMPLETED" | "CANCELLED" | undefined;
    description?: string | undefined;
    dateAd?: string | undefined;
    amount?: number | undefined;
    debitAccountId?: string | undefined;
    creditAccountId?: string | undefined;
    dateBs?: string | undefined;
    category?: "INCOME" | "EXPENSE" | "TRANSFER" | "INVESTMENT" | "HAND_OUTS" | undefined;
    partyName?: string | undefined;
    reference?: string | undefined;
}>;
export type CreateTransactionDTO = z.infer<typeof CreateTransactionSchema>;
export type UpdateTransactionDTO = z.infer<typeof UpdateTransactionSchema>;
